### PR TITLE
impl more size hint

### PR DESCRIPTION
**Pull request by thiolliere**
related https://github.com/paritytech/parity-codec/issues/87

This PR is based on gui-impl-for-u8 for the moment, it introduce for size_hint implementation for different types.

question:
* Do we want to implement size hint when it cost iterating on all elements ? (for instance Vec, BTreeMap, BTreeSet)

depending on the answer I'll update test.

### CODE REVIEW

**Comment by bkchr** [comment]
I think we should not loop, at the end it is more costly then just re-allocating.

**Comment by thiolliere** [comment]
Yes agree at some point I was wondering if it would be worth introducing another size_hint which doesn't take any argument so a set of this could just ask for the maximum size 🤔

**Comment by thiolliere** [comment]
done

**Comment by bkchr** [comment]
I thought about the "maximum size" as well, but then we should drop `size_hint`. Because how would you decide which to call?

**Comment by thiolliere** [comment]
we could keep both:
* maximum_size() used on set of values
* size_hint(&self) used on individual values,

size_hint(&self) (thought maybe renamed) would be default implementation to maximum_size()

**Comment by bkchr** [comment]
Yeah sounds good, do you create an issue for this?

**Comment by thiolliere** [comment]
https://github.com/paritytech/parity-codec/issues/93

**Comment by bkchr** [comment]
ty

**Pull request merged**
